[build]
  # Simple no-op build so Netlify is happy
  command  = "echo build"
  publish  = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "20"
